/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildInfo : The response is a JSON object containing the following fields
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildInfo {
    #[serde(rename = "qt", skip_serializing_if = "Option::is_none")]
    pub qt: Option<String>,
    #[serde(rename = "libtorrent", skip_serializing_if = "Option::is_none")]
    pub libtorrent: Option<String>,
    #[serde(rename = "boost", skip_serializing_if = "Option::is_none")]
    pub boost: Option<String>,
    #[serde(rename = "openssl", skip_serializing_if = "Option::is_none")]
    pub openssl: Option<String>,
    #[serde(rename = "bitness", skip_serializing_if = "Option::is_none")]
    pub bitness: Option<i32>,
}

impl BuildInfo {
    /// The response is a JSON object containing the following fields
    pub fn new() -> BuildInfo {
        BuildInfo {
            qt: None,
            libtorrent: None,
            boost: None,
            openssl: None,
            bitness: None,
        }
    }
}

