/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MainData : The response is a JSON object with the following possible fields
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MainData {
    /// Response ID
    #[serde(rename = "rid", skip_serializing_if = "Option::is_none")]
    pub rid: Option<i64>,
    /// Whether the response contains all the data or partial data
    #[serde(rename = "full_update", skip_serializing_if = "Option::is_none")]
    pub full_update: Option<bool>,
    /// Property: torrent hash, value: same as [torrent list](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#get-torrent-list)
    #[serde(rename = "torrents", skip_serializing_if = "Option::is_none")]
    pub torrents: Option<std::collections::HashMap<String, models::TorrentInfo>>,
    /// List of hashes of torrents removed since last request
    #[serde(rename = "torrents_removed", skip_serializing_if = "Option::is_none")]
    pub torrents_removed: Option<Vec<String>>,
    /// Info for categories added since last request
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<std::collections::HashMap<String, models::TorrentsCategory>>,
    /// List of categories removed since last request
    #[serde(rename = "categories_removed", skip_serializing_if = "Option::is_none")]
    pub categories_removed: Option<Vec<String>>,
    /// List of tags added since last request
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// List of tags removed since last request
    #[serde(rename = "tags_removed", skip_serializing_if = "Option::is_none")]
    pub tags_removed: Option<Vec<String>>,
    #[serde(rename = "server_state", skip_serializing_if = "Option::is_none")]
    pub server_state: Option<Box<models::TransferInfo>>,
}

impl MainData {
    /// The response is a JSON object with the following possible fields
    pub fn new() -> MainData {
        MainData {
            rid: None,
            full_update: None,
            torrents: None,
            torrents_removed: None,
            categories: None,
            categories_removed: None,
            tags: None,
            tags_removed: None,
            server_state: None,
        }
    }
}

