/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};

/// Preferences : Possible fields:
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preferences {
    /// Currently selected language (e.g. en_GB for English)
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    /// True if a subfolder should be created when adding a torrent
    #[serde(rename = "create_subfolder_enabled", skip_serializing_if = "Option::is_none")]
    pub create_subfolder_enabled: Option<bool>,
    /// True if torrents should be added in a Paused state
    #[serde(rename = "start_paused_enabled", skip_serializing_if = "Option::is_none")]
    pub start_paused_enabled: Option<bool>,
    /// TODO
    #[serde(rename = "auto_delete_mode", skip_serializing_if = "Option::is_none")]
    pub auto_delete_mode: Option<i32>,
    /// True if disk space should be pre-allocated for all files
    #[serde(rename = "preallocate_all", skip_serializing_if = "Option::is_none")]
    pub preallocate_all: Option<bool>,
    /// True if \".!qB\" should be appended to incomplete files
    #[serde(rename = "incomplete_files_ext", skip_serializing_if = "Option::is_none")]
    pub incomplete_files_ext: Option<bool>,
    /// True if Automatic Torrent Management is enabled by default
    #[serde(rename = "auto_tmm_enabled", skip_serializing_if = "Option::is_none")]
    pub auto_tmm_enabled: Option<bool>,
    /// True if torrent should be relocated when its Category changes
    #[serde(rename = "torrent_changed_tmm_enabled", skip_serializing_if = "Option::is_none")]
    pub torrent_changed_tmm_enabled: Option<bool>,
    /// True if torrent should be relocated when the default save path changes
    #[serde(rename = "save_path_changed_tmm_enabled", skip_serializing_if = "Option::is_none")]
    pub save_path_changed_tmm_enabled: Option<bool>,
    /// True if torrent should be relocated when its Category's save path changes
    #[serde(rename = "category_changed_tmm_enabled", skip_serializing_if = "Option::is_none")]
    pub category_changed_tmm_enabled: Option<bool>,
    /// Default save path for torrents, separated by slashes
    #[serde(rename = "save_path", skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
    /// True if folder for incomplete torrents is enabled
    #[serde(rename = "temp_path_enabled", skip_serializing_if = "Option::is_none")]
    pub temp_path_enabled: Option<bool>,
    /// Path for incomplete torrents, separated by slashes
    #[serde(rename = "temp_path", skip_serializing_if = "Option::is_none")]
    pub temp_path: Option<String>,
    /// Property: directory to watch for torrent files, value: where torrents loaded from this directory should be downloaded to (see list of possible values below). Slashes are used as path separators; multiple key/value pairs can be specified  | Value                  | Description                       | | ---------------------- | --------------------------------- | | 0                      | Download to the monitored folder  | | 1                      | Download to the default save path | | \"/path/to/download/to\" | Download to this path             | 
    #[serde(rename = "scan_dirs", skip_serializing_if = "Option::is_none")]
    pub scan_dirs: Option<std::collections::HashMap<String, models::PreferencesScanDirsValue>>,
    /// Path to directory to copy .torrent files to. Slashes are used as path separators
    #[serde(rename = "export_dir", skip_serializing_if = "Option::is_none")]
    pub export_dir: Option<String>,
    /// Path to directory to copy .torrent files of completed downloads to. Slashes are used as path separators
    #[serde(rename = "export_dir_fin", skip_serializing_if = "Option::is_none")]
    pub export_dir_fin: Option<String>,
    /// True if e-mail notification should be enabled
    #[serde(rename = "mail_notification_enabled", skip_serializing_if = "Option::is_none")]
    pub mail_notification_enabled: Option<bool>,
    /// e-mail where notifications should originate from
    #[serde(rename = "mail_notification_sender", skip_serializing_if = "Option::is_none")]
    pub mail_notification_sender: Option<String>,
    /// e-mail to send notifications to
    #[serde(rename = "mail_notification_email", skip_serializing_if = "Option::is_none")]
    pub mail_notification_email: Option<String>,
    /// smtp server for e-mail notifications
    #[serde(rename = "mail_notification_smtp", skip_serializing_if = "Option::is_none")]
    pub mail_notification_smtp: Option<String>,
    /// True if smtp server requires SSL connection
    #[serde(rename = "mail_notification_ssl_enabled", skip_serializing_if = "Option::is_none")]
    pub mail_notification_ssl_enabled: Option<bool>,
    /// True if smtp server requires authentication
    #[serde(rename = "mail_notification_auth_enabled", skip_serializing_if = "Option::is_none")]
    pub mail_notification_auth_enabled: Option<bool>,
    /// Username for smtp authentication
    #[serde(rename = "mail_notification_username", skip_serializing_if = "Option::is_none")]
    pub mail_notification_username: Option<String>,
    /// Password for smtp authentication
    #[serde(rename = "mail_notification_password", skip_serializing_if = "Option::is_none")]
    pub mail_notification_password: Option<String>,
    /// True if external program should be run after torrent has finished downloading
    #[serde(rename = "autorun_enabled", skip_serializing_if = "Option::is_none")]
    pub autorun_enabled: Option<bool>,
    /// Program path/name/arguments to run if `autorun_enabled` is enabled; path is separated by slashes; you can use `%f` and `%n` arguments, which will be expanded by qBittorent as path_to_torrent_file and torrent_name (from the GUI; not the .torrent file name) respectively
    #[serde(rename = "autorun_program", skip_serializing_if = "Option::is_none")]
    pub autorun_program: Option<String>,
    /// True if torrent queuing is enabled
    #[serde(rename = "queueing_enabled", skip_serializing_if = "Option::is_none")]
    pub queueing_enabled: Option<bool>,
    /// Maximum number of active simultaneous downloads
    #[serde(rename = "max_active_downloads", skip_serializing_if = "Option::is_none")]
    pub max_active_downloads: Option<i64>,
    /// Maximum number of active simultaneous downloads and uploads
    #[serde(rename = "max_active_torrents", skip_serializing_if = "Option::is_none")]
    pub max_active_torrents: Option<i64>,
    /// Maximum number of active simultaneous uploads
    #[serde(rename = "max_active_uploads", skip_serializing_if = "Option::is_none")]
    pub max_active_uploads: Option<i64>,
    /// If true torrents w/o any activity (stalled ones) will not be counted towards `max_active_*` limits; see [dont_count_slow_torrents](https://www.libtorrent.org/reference-Settings.html#dont_count_slow_torrents) for more information
    #[serde(rename = "dont_count_slow_torrents", skip_serializing_if = "Option::is_none")]
    pub dont_count_slow_torrents: Option<bool>,
    /// Download rate in KiB/s for a torrent to be considered \"slow\"
    #[serde(rename = "slow_torrent_dl_rate_threshold", skip_serializing_if = "Option::is_none")]
    pub slow_torrent_dl_rate_threshold: Option<i64>,
    /// Upload rate in KiB/s for a torrent to be considered \"slow\"
    #[serde(rename = "slow_torrent_ul_rate_threshold", skip_serializing_if = "Option::is_none")]
    pub slow_torrent_ul_rate_threshold: Option<i64>,
    /// Seconds a torrent should be inactive before considered \"slow\"
    #[serde(rename = "slow_torrent_inactive_timer", skip_serializing_if = "Option::is_none")]
    pub slow_torrent_inactive_timer: Option<i64>,
    /// True if share ratio limit is enabled
    #[serde(rename = "max_ratio_enabled", skip_serializing_if = "Option::is_none")]
    pub max_ratio_enabled: Option<bool>,
    /// Get the global share ratio limit
    #[serde(rename = "max_ratio", skip_serializing_if = "Option::is_none")]
    pub max_ratio: Option<f32>,
    /// Action performed when a torrent reaches the maximum share ratio. See list of possible values here below.  | Value | Description    | | ----- | -------------- | | 0     | Pause torrent  | | 1     | Remove torrent | 
    #[serde(rename = "max_ratio_act", skip_serializing_if = "Option::is_none")]
    pub max_ratio_act: Option<MaxRatioAct>,
    /// Port for incoming connections
    #[serde(rename = "listen_port", skip_serializing_if = "Option::is_none")]
    pub listen_port: Option<i32>,
    /// True if UPnP/NAT-PMP is enabled
    #[serde(rename = "upnp", skip_serializing_if = "Option::is_none")]
    pub upnp: Option<bool>,
    /// True if the port is randomly selected
    #[serde(rename = "random_port", skip_serializing_if = "Option::is_none")]
    pub random_port: Option<bool>,
    /// Global download speed limit in KiB/s; `-1` means no limit is applied
    #[serde(rename = "dl_limit", skip_serializing_if = "Option::is_none")]
    pub dl_limit: Option<i64>,
    /// Global upload speed limit in KiB/s; `-1` means no limit is applied
    #[serde(rename = "up_limit", skip_serializing_if = "Option::is_none")]
    pub up_limit: Option<i64>,
    /// Maximum global number of simultaneous connections
    #[serde(rename = "max_connec", skip_serializing_if = "Option::is_none")]
    pub max_connec: Option<i64>,
    /// Maximum number of simultaneous connections per torrent
    #[serde(rename = "max_connec_per_torrent", skip_serializing_if = "Option::is_none")]
    pub max_connec_per_torrent: Option<i64>,
    /// Maximum number of upload slots
    #[serde(rename = "max_uploads", skip_serializing_if = "Option::is_none")]
    pub max_uploads: Option<i64>,
    /// Maximum number of upload slots per torrent
    #[serde(rename = "max_uploads_per_torrent", skip_serializing_if = "Option::is_none")]
    pub max_uploads_per_torrent: Option<i64>,
    /// Timeout in seconds for a `stopped` announce request to trackers
    #[serde(rename = "stop_tracker_timeout", skip_serializing_if = "Option::is_none")]
    pub stop_tracker_timeout: Option<i64>,
    /// True if the advanced libtorrent option `piece_extent_affinity` is enabled
    #[serde(rename = "enable_piece_extent_affinity", skip_serializing_if = "Option::is_none")]
    pub enable_piece_extent_affinity: Option<bool>,
    /// Bittorrent Protocol to use (see list of possible values below)  | Value | Description | | ----- | ----------- | | 0     | TCP and μTP | | 1     | TCP         | | 2     | μTP         | 
    #[serde(rename = "bittorrent_protocol", skip_serializing_if = "Option::is_none")]
    pub bittorrent_protocol: Option<BittorrentProtocol>,
    /// True if `[du]l_limit` should be applied to uTP connections; this option is only available in qBittorent built against libtorrent version 0.16.X and higher
    #[serde(rename = "limit_utp_rate", skip_serializing_if = "Option::is_none")]
    pub limit_utp_rate: Option<bool>,
    /// True if `[du]l_limit` should be applied to estimated TCP overhead (service data: e.g. packet headers)
    #[serde(rename = "limit_tcp_overhead", skip_serializing_if = "Option::is_none")]
    pub limit_tcp_overhead: Option<bool>,
    /// True if `[du]l_limit` should be applied to peers on the LAN
    #[serde(rename = "limit_lan_peers", skip_serializing_if = "Option::is_none")]
    pub limit_lan_peers: Option<bool>,
    /// Alternative global download speed limit in KiB/s
    #[serde(rename = "alt_dl_limit", skip_serializing_if = "Option::is_none")]
    pub alt_dl_limit: Option<i64>,
    /// Alternative global upload speed limit in KiB/s
    #[serde(rename = "alt_up_limit", skip_serializing_if = "Option::is_none")]
    pub alt_up_limit: Option<i64>,
    /// True if alternative limits should be applied according to schedule
    #[serde(rename = "scheduler_enabled", skip_serializing_if = "Option::is_none")]
    pub scheduler_enabled: Option<bool>,
    /// Scheduler starting hour
    #[serde(rename = "schedule_from_hour", skip_serializing_if = "Option::is_none")]
    pub schedule_from_hour: Option<i32>,
    /// Scheduler starting minute
    #[serde(rename = "schedule_from_min", skip_serializing_if = "Option::is_none")]
    pub schedule_from_min: Option<i32>,
    /// Scheduler ending hour
    #[serde(rename = "schedule_to_hour", skip_serializing_if = "Option::is_none")]
    pub schedule_to_hour: Option<i32>,
    /// Scheduler ending minute
    #[serde(rename = "schedule_to_min", skip_serializing_if = "Option::is_none")]
    pub schedule_to_min: Option<i32>,
    /// Scheduler days. See possible values here below  | Value | Description     | | ----- | --------------- | | 0     | Every day       | | 1     | Every weekday   | | 2     | Every weekend   | | 3     | Every Monday    | | 4     | Every Tuesday   | | 5     | Every Wednesday | | 6     | Every Thursday  | | 7     | Every Friday    | | 8     | Every Saturday  | | 9     | Every Sunday    | 
    #[serde(rename = "scheduler_days", skip_serializing_if = "Option::is_none")]
    pub scheduler_days: Option<SchedulerDays>,
    /// True if DHT is enabled
    #[serde(rename = "dht", skip_serializing_if = "Option::is_none")]
    pub dht: Option<bool>,
    /// True if PeX is enabled
    #[serde(rename = "pex", skip_serializing_if = "Option::is_none")]
    pub pex: Option<bool>,
    /// True if LSD is enabled
    #[serde(rename = "lsd", skip_serializing_if = "Option::is_none")]
    pub lsd: Option<bool>,
    /// See list of possible values here below  | Value | Description          | | ----- | -------------------- | | 0     | Prefer encryption    | | 1     | Force encryption on  | | 2     | Force encryption off | 
    #[serde(rename = "encryption", skip_serializing_if = "Option::is_none")]
    pub encryption: Option<Encryption>,
    /// If true anonymous mode will be enabled; read more [here](https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode); this option is only available in qBittorent built against libtorrent version 0.16.X and higher
    #[serde(rename = "anonymous_mode", skip_serializing_if = "Option::is_none")]
    pub anonymous_mode: Option<bool>,
    /// See list of possible values here below  | Value | Description                         | | ----- | ----------------------------------- | | -1    | Proxy is disabled                   | | 0     | Prefer encryption                   | | 1     | HTTP proxy without authentication   | | 2     | SOCKS5 proxy without authentication | | 3     | HTTP proxy with authentication      | | 4     | SOCKS5 proxy with authentication    | | 5     | SOCKS4 proxy without authentication | 
    #[serde(rename = "proxy_type", skip_serializing_if = "Option::is_none")]
    pub proxy_type: Option<ProxyType>,
    /// Proxy IP address or domain name
    #[serde(rename = "proxy_ip", skip_serializing_if = "Option::is_none")]
    pub proxy_ip: Option<String>,
    /// Proxy port
    #[serde(rename = "proxy_port", skip_serializing_if = "Option::is_none")]
    pub proxy_port: Option<i32>,
    /// True if peer and web seed connections should be proxified; this option will have any effect only in qBittorent built against libtorrent version 0.16.X and higher
    #[serde(rename = "proxy_peer_connections", skip_serializing_if = "Option::is_none")]
    pub proxy_peer_connections: Option<bool>,
    /// True proxy requires authentication; doesn't apply to SOCKS4 proxies
    #[serde(rename = "proxy_auth_enabled", skip_serializing_if = "Option::is_none")]
    pub proxy_auth_enabled: Option<bool>,
    /// Username for proxy authentication
    #[serde(rename = "proxy_username", skip_serializing_if = "Option::is_none")]
    pub proxy_username: Option<String>,
    /// Password for proxy authentication
    #[serde(rename = "proxy_password", skip_serializing_if = "Option::is_none")]
    pub proxy_password: Option<String>,
    /// True if proxy is only used for torrents
    #[serde(rename = "proxy_torrents_only", skip_serializing_if = "Option::is_none")]
    pub proxy_torrents_only: Option<bool>,
    /// True if external IP filter should be enabled
    #[serde(rename = "ip_filter_enabled", skip_serializing_if = "Option::is_none")]
    pub ip_filter_enabled: Option<bool>,
    /// Path to IP filter file (.dat, .p2p, .p2b files are supported); path is separated by slashes
    #[serde(rename = "ip_filter_path", skip_serializing_if = "Option::is_none")]
    pub ip_filter_path: Option<String>,
    /// True if IP filters are applied to trackers
    #[serde(rename = "ip_filter_trackers", skip_serializing_if = "Option::is_none")]
    pub ip_filter_trackers: Option<bool>,
    /// Comma-separated list of domains to accept when performing Host header validation
    #[serde(rename = "web_ui_domain_list", skip_serializing_if = "Option::is_none")]
    pub web_ui_domain_list: Option<Vec<String>>,
    /// IP address to use for the WebUI
    #[serde(rename = "web_ui_address", skip_serializing_if = "Option::is_none")]
    pub web_ui_address: Option<String>,
    /// WebUI port
    #[serde(rename = "web_ui_port", skip_serializing_if = "Option::is_none")]
    pub web_ui_port: Option<i32>,
    /// True if UPnP is used for the WebUI port
    #[serde(rename = "web_ui_upnp", skip_serializing_if = "Option::is_none")]
    pub web_ui_upnp: Option<bool>,
    /// WebUI username
    #[serde(rename = "web_ui_username", skip_serializing_if = "Option::is_none")]
    pub web_ui_username: Option<String>,
    /// True if WebUI CSRF protection is enabled
    #[serde(rename = "web_ui_csrf_protection_enabled", skip_serializing_if = "Option::is_none")]
    pub web_ui_csrf_protection_enabled: Option<bool>,
    /// True if WebUI clickjacking protection is enabled
    #[serde(rename = "web_ui_clickjacking_protection_enabled", skip_serializing_if = "Option::is_none")]
    pub web_ui_clickjacking_protection_enabled: Option<bool>,
    /// True if WebUI cookie `Secure` flag is enabled
    #[serde(rename = "web_ui_secure_cookie_enabled", skip_serializing_if = "Option::is_none")]
    pub web_ui_secure_cookie_enabled: Option<bool>,
    /// Maximum number of authentication failures before WebUI access ban
    #[serde(rename = "web_ui_max_auth_fail_count", skip_serializing_if = "Option::is_none")]
    pub web_ui_max_auth_fail_count: Option<i64>,
    /// WebUI access ban duration in seconds
    #[serde(rename = "web_ui_ban_duration", skip_serializing_if = "Option::is_none")]
    pub web_ui_ban_duration: Option<i64>,
    /// Seconds until WebUI is automatically signed off
    #[serde(rename = "web_ui_session_timeout", skip_serializing_if = "Option::is_none")]
    pub web_ui_session_timeout: Option<i64>,
    /// True if WebUI host header validation is enabled
    #[serde(rename = "web_ui_host_header_validation_enabled", skip_serializing_if = "Option::is_none")]
    pub web_ui_host_header_validation_enabled: Option<bool>,
    /// True if authentication challenge for loopback address (127.0.0.1) should be disabled
    #[serde(rename = "bypass_local_auth", skip_serializing_if = "Option::is_none")]
    pub bypass_local_auth: Option<bool>,
    /// True if webui authentication should be bypassed for clients whose ip resides within (at least) one of the subnets on the whitelist
    #[serde(rename = "bypass_auth_subnet_whitelist_enabled", skip_serializing_if = "Option::is_none")]
    pub bypass_auth_subnet_whitelist_enabled: Option<bool>,
    /// (White)list of ipv4/ipv6 subnets for which webui authentication should be bypassed; list entries are separated by commas
    #[serde(rename = "bypass_auth_subnet_whitelist", skip_serializing_if = "Option::is_none")]
    pub bypass_auth_subnet_whitelist: Option<Vec<String>>,
    /// True if an alternative WebUI should be used
    #[serde(rename = "alternative_webui_enabled", skip_serializing_if = "Option::is_none")]
    pub alternative_webui_enabled: Option<bool>,
    /// File path to the alternative WebUI
    #[serde(rename = "alternative_webui_path", skip_serializing_if = "Option::is_none")]
    pub alternative_webui_path: Option<String>,
    /// True if WebUI HTTPS access is enabled
    #[serde(rename = "use_https", skip_serializing_if = "Option::is_none")]
    pub use_https: Option<bool>,
    /// For API < v2.0.1: SSL keyfile contents (this is a not a path)
    #[serde(rename = "ssl_key", skip_serializing_if = "Option::is_none")]
    pub ssl_key: Option<String>,
    /// For API < v2.0.1: SSL certificate contents (this is a not a path)
    #[serde(rename = "ssl_cert", skip_serializing_if = "Option::is_none")]
    pub ssl_cert: Option<String>,
    /// For API ≥ v2.0.1: Path to SSL keyfile
    #[serde(rename = "web_ui_https_key_path", skip_serializing_if = "Option::is_none")]
    pub web_ui_https_key_path: Option<String>,
    /// For API ≥ v2.0.1: Path to SSL certificate
    #[serde(rename = "web_ui_https_cert_path", skip_serializing_if = "Option::is_none")]
    pub web_ui_https_cert_path: Option<String>,
    /// True if server DNS should be updated dynamically
    #[serde(rename = "dyndns_enabled", skip_serializing_if = "Option::is_none")]
    pub dyndns_enabled: Option<bool>,
    /// See list of possible values here below  | Value | Description | | ----- | ----------- | | 0     | Use DyDNS   | | 1     | Use NOIP    | 
    #[serde(rename = "dyndns_service", skip_serializing_if = "Option::is_none")]
    pub dyndns_service: Option<DyndnsService>,
    /// Username for DDNS service
    #[serde(rename = "dyndns_username", skip_serializing_if = "Option::is_none")]
    pub dyndns_username: Option<String>,
    /// Password for DDNS service
    #[serde(rename = "dyndns_password", skip_serializing_if = "Option::is_none")]
    pub dyndns_password: Option<String>,
    /// Your DDNS domain name
    #[serde(rename = "dyndns_domain", skip_serializing_if = "Option::is_none")]
    pub dyndns_domain: Option<String>,
    /// RSS refresh interval
    #[serde(rename = "rss_refresh_interval", skip_serializing_if = "Option::is_none")]
    pub rss_refresh_interval: Option<i64>,
    /// Max stored articles per RSS feed
    #[serde(rename = "rss_max_articles_per_feed", skip_serializing_if = "Option::is_none")]
    pub rss_max_articles_per_feed: Option<i64>,
    /// Enable processing of RSS feeds
    #[serde(rename = "rss_processing_enabled", skip_serializing_if = "Option::is_none")]
    pub rss_processing_enabled: Option<bool>,
    /// Enable auto-downloading of torrents from the RSS feeds
    #[serde(rename = "rss_auto_downloading_enabled", skip_serializing_if = "Option::is_none")]
    pub rss_auto_downloading_enabled: Option<bool>,
    /// For API ≥ v2.5.1: Enable downloading of repack/proper Episodes
    #[serde(rename = "rss_download_repack_proper_episodes", skip_serializing_if = "Option::is_none")]
    pub rss_download_repack_proper_episodes: Option<bool>,
    /// For API ≥ v2.5.1: List of RSS Smart Episode Filters
    #[serde(rename = "rss_smart_episode_filters", skip_serializing_if = "Option::is_none")]
    pub rss_smart_episode_filters: Option<String>,
    /// Enable automatic adding of trackers to new torrents
    #[serde(rename = "add_trackers_enabled", skip_serializing_if = "Option::is_none")]
    pub add_trackers_enabled: Option<bool>,
    /// List of trackers to add to new torrent
    #[serde(rename = "add_trackers", skip_serializing_if = "Option::is_none")]
    pub add_trackers: Option<String>,
    /// For API ≥ v2.5.1: Enable custom http headers
    #[serde(rename = "web_ui_use_custom_http_headers_enabled", skip_serializing_if = "Option::is_none")]
    pub web_ui_use_custom_http_headers_enabled: Option<bool>,
    /// For API ≥ v2.5.1: List of custom http headers
    #[serde(rename = "web_ui_custom_http_headers", skip_serializing_if = "Option::is_none")]
    pub web_ui_custom_http_headers: Option<String>,
    /// True enables max seeding time
    #[serde(rename = "max_seeding_time_enabled", skip_serializing_if = "Option::is_none")]
    pub max_seeding_time_enabled: Option<bool>,
    /// Number of minutes to seed a torrent
    #[serde(rename = "max_seeding_time", skip_serializing_if = "Option::is_none")]
    pub max_seeding_time: Option<i64>,
    /// TODO
    #[serde(rename = "announce_ip", skip_serializing_if = "Option::is_none")]
    pub announce_ip: Option<String>,
    /// True always announce to all tiers
    #[serde(rename = "announce_to_all_tiers", skip_serializing_if = "Option::is_none")]
    pub announce_to_all_tiers: Option<bool>,
    /// True always announce to all trackers in a tier
    #[serde(rename = "announce_to_all_trackers", skip_serializing_if = "Option::is_none")]
    pub announce_to_all_trackers: Option<bool>,
    /// Number of asynchronous I/O threads
    #[serde(rename = "async_io_threads", skip_serializing_if = "Option::is_none")]
    pub async_io_threads: Option<i64>,
    /// List of banned IPs
    #[serde(rename = "banned_IPs", skip_serializing_if = "Option::is_none")]
    pub banned_ips: Option<String>,
    /// Outstanding memory when checking torrents in MiB
    #[serde(rename = "checking_memory_use", skip_serializing_if = "Option::is_none")]
    pub checking_memory_use: Option<i64>,
    /// IP Address to bind to. Empty String means All addresses
    #[serde(rename = "current_interface_address", skip_serializing_if = "Option::is_none")]
    pub current_interface_address: Option<String>,
    /// Network Interface used
    #[serde(rename = "current_network_interface", skip_serializing_if = "Option::is_none")]
    pub current_network_interface: Option<String>,
    /// Disk cache used in MiB
    #[serde(rename = "disk_cache", skip_serializing_if = "Option::is_none")]
    pub disk_cache: Option<i64>,
    /// Disk cache expiry interval in seconds
    #[serde(rename = "disk_cache_ttl", skip_serializing_if = "Option::is_none")]
    pub disk_cache_ttl: Option<i64>,
    /// Port used for embedded tracker
    #[serde(rename = "embedded_tracker_port", skip_serializing_if = "Option::is_none")]
    pub embedded_tracker_port: Option<i32>,
    /// True enables coalesce reads & writes
    #[serde(rename = "enable_coalesce_read_write", skip_serializing_if = "Option::is_none")]
    pub enable_coalesce_read_write: Option<bool>,
    /// True enables embedded tracker
    #[serde(rename = "enable_embedded_tracker", skip_serializing_if = "Option::is_none")]
    pub enable_embedded_tracker: Option<bool>,
    /// True allows multiple connections from the same IP address
    #[serde(rename = "enable_multi_connections_from_same_ip", skip_serializing_if = "Option::is_none")]
    pub enable_multi_connections_from_same_ip: Option<bool>,
    /// True enables os cache
    #[serde(rename = "enable_os_cache", skip_serializing_if = "Option::is_none")]
    pub enable_os_cache: Option<bool>,
    /// True enables sending of upload piece suggestions
    #[serde(rename = "enable_upload_suggestions", skip_serializing_if = "Option::is_none")]
    pub enable_upload_suggestions: Option<bool>,
    /// File pool size
    #[serde(rename = "file_pool_size", skip_serializing_if = "Option::is_none")]
    pub file_pool_size: Option<i64>,
    /// Maximal outgoing port (0: Disabled)
    #[serde(rename = "outgoing_ports_max", skip_serializing_if = "Option::is_none")]
    pub outgoing_ports_max: Option<i32>,
    /// Minimal outgoing port (0: Disabled)
    #[serde(rename = "outgoing_ports_min", skip_serializing_if = "Option::is_none")]
    pub outgoing_ports_min: Option<i32>,
    /// True rechecks torrents on completion
    #[serde(rename = "recheck_completed_torrents", skip_serializing_if = "Option::is_none")]
    pub recheck_completed_torrents: Option<bool>,
    /// True resolves peer countries
    #[serde(rename = "resolve_peer_countries", skip_serializing_if = "Option::is_none")]
    pub resolve_peer_countries: Option<bool>,
    /// Save resume data interval in min
    #[serde(rename = "save_resume_data_interval", skip_serializing_if = "Option::is_none")]
    pub save_resume_data_interval: Option<i64>,
    /// Send buffer low watermark in KiB
    #[serde(rename = "send_buffer_low_watermark", skip_serializing_if = "Option::is_none")]
    pub send_buffer_low_watermark: Option<i64>,
    /// Send buffer watermark in KiB
    #[serde(rename = "send_buffer_watermark", skip_serializing_if = "Option::is_none")]
    pub send_buffer_watermark: Option<i64>,
    /// Send buffer watermark factor in percent
    #[serde(rename = "send_buffer_watermark_factor", skip_serializing_if = "Option::is_none")]
    pub send_buffer_watermark_factor: Option<i32>,
    /// Socket backlog size
    #[serde(rename = "socket_backlog_size", skip_serializing_if = "Option::is_none")]
    pub socket_backlog_size: Option<i64>,
    /// Upload choking algorithm used (see list of possible values below)  | Value | Description    | | ----- | -------------- | | 0     | Round-robin    | | 1     | Fastest upload | | 2     | Anti-leech     | 
    #[serde(rename = "upload_choking_algorithm", skip_serializing_if = "Option::is_none")]
    pub upload_choking_algorithm: Option<UploadChokingAlgorithm>,
    /// Upload slots behavior used (see list of possible values below)  | Value | Description       | | ----- | ----------------- | | 0     | Fixed slots       | | 1     | Upload rate based | 
    #[serde(rename = "upload_slots_behavior", skip_serializing_if = "Option::is_none")]
    pub upload_slots_behavior: Option<UploadSlotsBehavior>,
    /// UPnP lease duration (0: Permanent lease)
    #[serde(rename = "upnp_lease_duration", skip_serializing_if = "Option::is_none")]
    pub upnp_lease_duration: Option<i64>,
    /// μTP-TCP mixed mode algorithm (see list of possible values below)  | Value | Description       | | ----- | ----------------- | | 0     | Prefer TCP        | | 1     | Peer proportional | 
    #[serde(rename = "utp_tcp_mixed_mode", skip_serializing_if = "Option::is_none")]
    pub utp_tcp_mixed_mode: Option<UtpTcpMixedMode>,
}

impl Preferences {
    /// Possible fields:
    pub fn new() -> Preferences {
        Preferences {
            locale: None,
            create_subfolder_enabled: None,
            start_paused_enabled: None,
            auto_delete_mode: None,
            preallocate_all: None,
            incomplete_files_ext: None,
            auto_tmm_enabled: None,
            torrent_changed_tmm_enabled: None,
            save_path_changed_tmm_enabled: None,
            category_changed_tmm_enabled: None,
            save_path: None,
            temp_path_enabled: None,
            temp_path: None,
            scan_dirs: None,
            export_dir: None,
            export_dir_fin: None,
            mail_notification_enabled: None,
            mail_notification_sender: None,
            mail_notification_email: None,
            mail_notification_smtp: None,
            mail_notification_ssl_enabled: None,
            mail_notification_auth_enabled: None,
            mail_notification_username: None,
            mail_notification_password: None,
            autorun_enabled: None,
            autorun_program: None,
            queueing_enabled: None,
            max_active_downloads: None,
            max_active_torrents: None,
            max_active_uploads: None,
            dont_count_slow_torrents: None,
            slow_torrent_dl_rate_threshold: None,
            slow_torrent_ul_rate_threshold: None,
            slow_torrent_inactive_timer: None,
            max_ratio_enabled: None,
            max_ratio: None,
            max_ratio_act: None,
            listen_port: None,
            upnp: None,
            random_port: None,
            dl_limit: None,
            up_limit: None,
            max_connec: None,
            max_connec_per_torrent: None,
            max_uploads: None,
            max_uploads_per_torrent: None,
            stop_tracker_timeout: None,
            enable_piece_extent_affinity: None,
            bittorrent_protocol: None,
            limit_utp_rate: None,
            limit_tcp_overhead: None,
            limit_lan_peers: None,
            alt_dl_limit: None,
            alt_up_limit: None,
            scheduler_enabled: None,
            schedule_from_hour: None,
            schedule_from_min: None,
            schedule_to_hour: None,
            schedule_to_min: None,
            scheduler_days: None,
            dht: None,
            pex: None,
            lsd: None,
            encryption: None,
            anonymous_mode: None,
            proxy_type: None,
            proxy_ip: None,
            proxy_port: None,
            proxy_peer_connections: None,
            proxy_auth_enabled: None,
            proxy_username: None,
            proxy_password: None,
            proxy_torrents_only: None,
            ip_filter_enabled: None,
            ip_filter_path: None,
            ip_filter_trackers: None,
            web_ui_domain_list: None,
            web_ui_address: None,
            web_ui_port: None,
            web_ui_upnp: None,
            web_ui_username: None,
            web_ui_csrf_protection_enabled: None,
            web_ui_clickjacking_protection_enabled: None,
            web_ui_secure_cookie_enabled: None,
            web_ui_max_auth_fail_count: None,
            web_ui_ban_duration: None,
            web_ui_session_timeout: None,
            web_ui_host_header_validation_enabled: None,
            bypass_local_auth: None,
            bypass_auth_subnet_whitelist_enabled: None,
            bypass_auth_subnet_whitelist: None,
            alternative_webui_enabled: None,
            alternative_webui_path: None,
            use_https: None,
            ssl_key: None,
            ssl_cert: None,
            web_ui_https_key_path: None,
            web_ui_https_cert_path: None,
            dyndns_enabled: None,
            dyndns_service: None,
            dyndns_username: None,
            dyndns_password: None,
            dyndns_domain: None,
            rss_refresh_interval: None,
            rss_max_articles_per_feed: None,
            rss_processing_enabled: None,
            rss_auto_downloading_enabled: None,
            rss_download_repack_proper_episodes: None,
            rss_smart_episode_filters: None,
            add_trackers_enabled: None,
            add_trackers: None,
            web_ui_use_custom_http_headers_enabled: None,
            web_ui_custom_http_headers: None,
            max_seeding_time_enabled: None,
            max_seeding_time: None,
            announce_ip: None,
            announce_to_all_tiers: None,
            announce_to_all_trackers: None,
            async_io_threads: None,
            banned_ips: None,
            checking_memory_use: None,
            current_interface_address: None,
            current_network_interface: None,
            disk_cache: None,
            disk_cache_ttl: None,
            embedded_tracker_port: None,
            enable_coalesce_read_write: None,
            enable_embedded_tracker: None,
            enable_multi_connections_from_same_ip: None,
            enable_os_cache: None,
            enable_upload_suggestions: None,
            file_pool_size: None,
            outgoing_ports_max: None,
            outgoing_ports_min: None,
            recheck_completed_torrents: None,
            resolve_peer_countries: None,
            save_resume_data_interval: None,
            send_buffer_low_watermark: None,
            send_buffer_watermark: None,
            send_buffer_watermark_factor: None,
            socket_backlog_size: None,
            upload_choking_algorithm: None,
            upload_slots_behavior: None,
            upnp_lease_duration: None,
            utp_tcp_mixed_mode: None,
        }
    }
}
/// Action performed when a torrent reaches the maximum share ratio. See list of possible values here below.  | Value | Description    | | ----- | -------------- | | 0     | Pause torrent  | | 1     | Remove torrent | 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaxRatioAct {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for MaxRatioAct {
    fn default() -> MaxRatioAct {
        Self::Variant0
    }
}
/// Bittorrent Protocol to use (see list of possible values below)  | Value | Description | | ----- | ----------- | | 0     | TCP and μTP | | 1     | TCP         | | 2     | μTP         | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum BittorrentProtocol {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
}

impl std::fmt::Display for BittorrentProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
        })
    }
}

impl Default for BittorrentProtocol {
    fn default() -> BittorrentProtocol {
        Self::Variant0
    }
}
/// Scheduler days. See possible values here below  | Value | Description     | | ----- | --------------- | | 0     | Every day       | | 1     | Every weekday   | | 2     | Every weekend   | | 3     | Every Monday    | | 4     | Every Tuesday   | | 5     | Every Wednesday | | 6     | Every Thursday  | | 7     | Every Friday    | | 8     | Every Saturday  | | 9     | Every Sunday    | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum SchedulerDays {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
    Variant5 = 5,
    Variant6 = 6,
    Variant7 = 7,
    Variant8 = 8,
    Variant9 = 9,
}

impl std::fmt::Display for SchedulerDays {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
            Self::Variant4 => "4",
            Self::Variant5 => "5",
            Self::Variant6 => "6",
            Self::Variant7 => "7",
            Self::Variant8 => "8",
            Self::Variant9 => "9",
        })
    }
}

impl Default for SchedulerDays {
    fn default() -> SchedulerDays {
        Self::Variant0
    }
}
/// See list of possible values here below  | Value | Description          | | ----- | -------------------- | | 0     | Prefer encryption    | | 1     | Force encryption on  | | 2     | Force encryption off | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum Encryption {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
}

impl std::fmt::Display for Encryption {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
        })
    }
}

impl Default for Encryption {
    fn default() -> Encryption {
        Self::Variant0
    }
}
/// See list of possible values here below  | Value | Description                         | | ----- | ----------------------------------- | | -1    | Proxy is disabled                   | | 0     | Prefer encryption                   | | 1     | HTTP proxy without authentication   | | 2     | SOCKS5 proxy without authentication | | 3     | HTTP proxy with authentication      | | 4     | SOCKS5 proxy with authentication    | | 5     | SOCKS4 proxy without authentication | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ProxyType {
    Variant1 = -1,
    Variant0 = 0,
    Variant12 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
    Variant5 = 5,
}

impl std::fmt::Display for ProxyType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant1 => "-1",
            Self::Variant0 => "0",
            Self::Variant12 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
            Self::Variant4 => "4",
            Self::Variant5 => "5",
        })
    }
}

impl Default for ProxyType {
    fn default() -> ProxyType {
        Self::Variant1
    }
}
/// See list of possible values here below  | Value | Description | | ----- | ----------- | | 0     | Use DyDNS   | | 1     | Use NOIP    | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum DyndnsService {
    Variant0 = 0,
    Variant1 = 1,
}

impl std::fmt::Display for DyndnsService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
        })
    }
}

impl Default for DyndnsService {
    fn default() -> DyndnsService {
        Self::Variant0
    }
}
/// Upload choking algorithm used (see list of possible values below)  | Value | Description    | | ----- | -------------- | | 0     | Round-robin    | | 1     | Fastest upload | | 2     | Anti-leech     | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum UploadChokingAlgorithm {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
}

impl std::fmt::Display for UploadChokingAlgorithm {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
        })
    }
}

impl Default for UploadChokingAlgorithm {
    fn default() -> UploadChokingAlgorithm {
        Self::Variant0
    }
}
/// Upload slots behavior used (see list of possible values below)  | Value | Description       | | ----- | ----------------- | | 0     | Fixed slots       | | 1     | Upload rate based | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum UploadSlotsBehavior {
    Variant0 = 0,
    Variant1 = 1,
}

impl std::fmt::Display for UploadSlotsBehavior {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
        })
    }
}

impl Default for UploadSlotsBehavior {
    fn default() -> UploadSlotsBehavior {
        Self::Variant0
    }
}
/// μTP-TCP mixed mode algorithm (see list of possible values below)  | Value | Description       | | ----- | ----------------- | | 0     | Prefer TCP        | | 1     | Peer proportional | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum UtpTcpMixedMode {
    Variant0 = 0,
    Variant1 = 1,
}

impl std::fmt::Display for UtpTcpMixedMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
        })
    }
}

impl Default for UtpTcpMixedMode {
    fn default() -> UtpTcpMixedMode {
        Self::Variant0
    }
}

