/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RssRuleDef : JSON encoded rule definition  Rule definition is JSON encoded dictionary with the following fields: | Field                     | Type   | Description                                             | | ------------------------- | ------ | ------------------------------------------------------- | | enabled                   | bool   | Whether the rule is enabled                             | | mustContain               | string | The substring that the torrent name must contain        | | mustNotContain            | string | The substring that the torrent name must not contain    | | useRegex                  | bool   | Enable regex mode in \"mustContain\" and \"mustNotContain\" | | episodeFilter             | string | Episode filter definition                               | | smartFilter               | bool   | Enable smart episode filter                             | | previouslyMatchedEpisodes | list   | The list of episode IDs already matched by smart filter | | affectedFeeds             | list   | The feed URLs the rule applied to                       | | ignoreDays                | number | Ignore sunsequent rule matches                          | | lastMatch                 | string | The rule last match time                                | | addPaused                 | bool   | Add matched torrent in paused mode                      | | assignedCategory          | string | Assign category to the torrent                          | | savePath                  | string | Save torrent to the given directory                     | 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RssRuleDef {
    /// Whether the rule is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// The substring that the torrent name must contain
    #[serde(rename = "mustContain", skip_serializing_if = "Option::is_none")]
    pub must_contain: Option<String>,
    /// The substring that the torrent name must not contain
    #[serde(rename = "mustNotContain", skip_serializing_if = "Option::is_none")]
    pub must_not_contain: Option<String>,
    /// Enable regex mode in \"mustContain\" and \"mustNotContain\"
    #[serde(rename = "useRegex", skip_serializing_if = "Option::is_none")]
    pub use_regex: Option<bool>,
    /// Episode filter definition
    #[serde(rename = "episodeFilter", skip_serializing_if = "Option::is_none")]
    pub episode_filter: Option<String>,
    /// Enable smart episode filter
    #[serde(rename = "smartFilter", skip_serializing_if = "Option::is_none")]
    pub smart_filter: Option<bool>,
    /// The list of episode IDs already matched by smart filter
    #[serde(rename = "previouslyMatchedEpisodes", skip_serializing_if = "Option::is_none")]
    pub previously_matched_episodes: Option<Vec<i64>>,
    /// The feed URLs the rule applied to
    #[serde(rename = "affectedFeeds", skip_serializing_if = "Option::is_none")]
    pub affected_feeds: Option<Vec<String>>,
    /// Ignore sunsequent rule matches
    #[serde(rename = "ignoreDays", skip_serializing_if = "Option::is_none")]
    pub ignore_days: Option<f64>,
    /// The rule last match time
    #[serde(rename = "lastMatch", skip_serializing_if = "Option::is_none")]
    pub last_match: Option<String>,
    /// Add matched torrent in paused mode
    #[serde(rename = "addPaused", skip_serializing_if = "Option::is_none")]
    pub add_paused: Option<bool>,
    /// Assign category to the torrent
    #[serde(rename = "assignedCategory", skip_serializing_if = "Option::is_none")]
    pub assigned_category: Option<String>,
    /// Save torrent to the given directory
    #[serde(rename = "savePath", skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
}

impl RssRuleDef {
    /// JSON encoded rule definition  Rule definition is JSON encoded dictionary with the following fields: | Field                     | Type   | Description                                             | | ------------------------- | ------ | ------------------------------------------------------- | | enabled                   | bool   | Whether the rule is enabled                             | | mustContain               | string | The substring that the torrent name must contain        | | mustNotContain            | string | The substring that the torrent name must not contain    | | useRegex                  | bool   | Enable regex mode in \"mustContain\" and \"mustNotContain\" | | episodeFilter             | string | Episode filter definition                               | | smartFilter               | bool   | Enable smart episode filter                             | | previouslyMatchedEpisodes | list   | The list of episode IDs already matched by smart filter | | affectedFeeds             | list   | The feed URLs the rule applied to                       | | ignoreDays                | number | Ignore sunsequent rule matches                          | | lastMatch                 | string | The rule last match time                                | | addPaused                 | bool   | Add matched torrent in paused mode                      | | assignedCategory          | string | Assign category to the torrent                          | | savePath                  | string | Save torrent to the given directory                     | 
    pub fn new() -> RssRuleDef {
        RssRuleDef {
            enabled: None,
            must_contain: None,
            must_not_contain: None,
            use_regex: None,
            episode_filter: None,
            smart_filter: None,
            previously_matched_episodes: None,
            affected_feeds: None,
            ignore_days: None,
            last_match: None,
            add_paused: None,
            assigned_category: None,
            save_path: None,
        }
    }
}

