/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TorrentInfo {
    /// Time (Unix Epoch) when the torrent was added to the client
    #[serde(rename = "added_on", skip_serializing_if = "Option::is_none")]
    pub added_on: Option<i64>,
    /// Amount of data left to download (bytes)
    #[serde(rename = "amount_left", skip_serializing_if = "Option::is_none")]
    pub amount_left: Option<i64>,
    /// Whether this torrent is managed by Automatic Torrent Management
    #[serde(rename = "auto_tmm", skip_serializing_if = "Option::is_none")]
    pub auto_tmm: Option<bool>,
    /// Percentage of file pieces currently available
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<f32>,
    /// Category of the torrent
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Amount of transfer data completed (bytes)
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<i64>,
    /// Time (Unix Epoch) when the torrent completed
    #[serde(rename = "completion_on", skip_serializing_if = "Option::is_none")]
    pub completion_on: Option<i64>,
    /// Absolute path of torrent content (root path for multifile torrents, absolute file path for singlefile torrents)
    #[serde(rename = "content_path", skip_serializing_if = "Option::is_none")]
    pub content_path: Option<String>,
    /// Torrent download speed limit (bytes/s). `-1` if ulimited.
    #[serde(rename = "dl_limit", skip_serializing_if = "Option::is_none")]
    pub dl_limit: Option<i64>,
    /// Torrent download speed (bytes/s)
    #[serde(rename = "dlspeed", skip_serializing_if = "Option::is_none")]
    pub dlspeed: Option<i64>,
    /// Amount of data downloaded
    #[serde(rename = "downloaded", skip_serializing_if = "Option::is_none")]
    pub downloaded: Option<i64>,
    /// Amount of data downloaded this session
    #[serde(rename = "downloaded_session", skip_serializing_if = "Option::is_none")]
    pub downloaded_session: Option<i64>,
    /// Torrent ETA (seconds)
    #[serde(rename = "eta", skip_serializing_if = "Option::is_none")]
    pub eta: Option<i64>,
    /// True if first last piece are prioritized
    #[serde(rename = "f_l_piece_prio", skip_serializing_if = "Option::is_none")]
    pub f_l_piece_prio: Option<bool>,
    /// True if force start is enabled for this torrent
    #[serde(rename = "force_start", skip_serializing_if = "Option::is_none")]
    pub force_start: Option<bool>,
    /// Torrent hash
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Last time (Unix Epoch) when a chunk was downloaded/uploaded
    #[serde(rename = "last_activity", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<i64>,
    /// Magnet URI corresponding to this torrent
    #[serde(rename = "magnet_uri", skip_serializing_if = "Option::is_none")]
    pub magnet_uri: Option<String>,
    /// Maximum share ratio until torrent is stopped from seeding/uploading
    #[serde(rename = "max_ratio", skip_serializing_if = "Option::is_none")]
    pub max_ratio: Option<f32>,
    /// Maximum seeding time (seconds) until torrent is stopped from seeding
    #[serde(rename = "max_seeding_time", skip_serializing_if = "Option::is_none")]
    pub max_seeding_time: Option<i64>,
    /// Torrent name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Number of seeds in the swarm
    #[serde(rename = "num_complete", skip_serializing_if = "Option::is_none")]
    pub num_complete: Option<i64>,
    /// Number of leechers in the swarm
    #[serde(rename = "num_incomplete", skip_serializing_if = "Option::is_none")]
    pub num_incomplete: Option<i64>,
    /// Number of leechers connected to
    #[serde(rename = "num_leechs", skip_serializing_if = "Option::is_none")]
    pub num_leechs: Option<i64>,
    /// Number of seeds connected to
    #[serde(rename = "num_seeds", skip_serializing_if = "Option::is_none")]
    pub num_seeds: Option<i64>,
    /// Torrent priority. Returns -1 if queuing is disabled or torrent is in seed mode
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i64>,
    /// Torrent progress (percentage/100)
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<f32>,
    /// Torrent share ratio. Max ratio value: 9999.
    #[serde(rename = "ratio", skip_serializing_if = "Option::is_none")]
    pub ratio: Option<f32>,
    /// TODO (what is different from max_ratio?)
    #[serde(rename = "ratio_limit", skip_serializing_if = "Option::is_none")]
    pub ratio_limit: Option<f32>,
    /// Time until the next tracker reannounce
    #[serde(rename = "reannounce", skip_serializing_if = "Option::is_none")]
    pub reannounce: Option<i64>,
    /// Path where this torrent's data is stored
    #[serde(rename = "save_path", skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
    /// Torrent elapsed time while complete (seconds)
    #[serde(rename = "seeding_time", skip_serializing_if = "Option::is_none")]
    pub seeding_time: Option<i64>,
    /// TODO (what is different from `max_seeding_time`?) seeding_time_limit is a per torrent setting, when Automatic Torrent Management is disabled, furthermore then max_seeding_time is set to seeding_time_limit for this torrent. If Automatic Torrent Management is enabled, the value is -2. And if max_seeding_time is unset it have a default value -1.
    #[serde(rename = "seeding_time_limit", skip_serializing_if = "Option::is_none")]
    pub seeding_time_limit: Option<i64>,
    /// Time (Unix Epoch) when this torrent was last seen complete
    #[serde(rename = "seen_complete", skip_serializing_if = "Option::is_none")]
    pub seen_complete: Option<i64>,
    /// True if sequential download is enabled
    #[serde(rename = "seq_dl", skip_serializing_if = "Option::is_none")]
    pub seq_dl: Option<bool>,
    /// Total size (bytes) of files selected for download
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// Torrent state. See table here below for the possible values  | Value              | Description                                                   | | ------------------ | ------------------------------------------------------------- | | error              | Some error occurred, applies to paused torrents               | | missingFiles       | Torrent data files is missing                                 | | uploading          | Torrent is being seeded and data is being transferred         | | pausedUP           | Torrent is paused and has finished downloading                | | queuedUP           | Queuing is enabled and torrent is queued for upload           | | stalledUP          | Torrent is being seeded, but no connection were made          | | checkingUP         | Torrent has finished downloading and is being checked         | | forcedUP           | Torrent is forced to uploading and ignore queue limit         | | allocating         | Torrent is allocating disk space for download                 | | downloading        | Torrent is being downloaded and data is being transferred     | | metaDL             | Torrent has just started downloading and is fetching metadata | | pausedDL           | Torrent is paused and has NOT finished downloading            | | queuedDL           | Queuing is enabled and torrent is queued for download         | | stalledDL          | Torrent is being downloaded, but no connection were made      | | checkingDL         | Same as checkingUP, but torrent has NOT finished downloading  | | forcedDL           | Torrent is forced to downloading to ignore queue limit        | | checkingResumeData | Checking resume data on qBt startup                           | | moving             | Torrent is moving to another location                         | | unknown            | Unknown status                                                | 
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// True if super seeding is enabled
    #[serde(rename = "super_seeding", skip_serializing_if = "Option::is_none")]
    pub super_seeding: Option<bool>,
    /// Comma-concatenated tag list of the torrent
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    /// Total active time (seconds)
    #[serde(rename = "time_active", skip_serializing_if = "Option::is_none")]
    pub time_active: Option<i64>,
    /// Total size (bytes) of all file in this torrent (including unselected ones)
    #[serde(rename = "total_size", skip_serializing_if = "Option::is_none")]
    pub total_size: Option<i64>,
    /// The first tracker with working status. Returns empty string if no tracker is working.
    #[serde(rename = "tracker", skip_serializing_if = "Option::is_none")]
    pub tracker: Option<String>,
    /// Torrent upload speed limit (bytes/s). `-1` if ulimited.
    #[serde(rename = "up_limit", skip_serializing_if = "Option::is_none")]
    pub up_limit: Option<i64>,
    /// Amount of data uploaded
    #[serde(rename = "uploaded", skip_serializing_if = "Option::is_none")]
    pub uploaded: Option<i64>,
    /// Amount of data uploaded this session
    #[serde(rename = "uploaded_session", skip_serializing_if = "Option::is_none")]
    pub uploaded_session: Option<i64>,
    /// Torrent upload speed (bytes/s)
    #[serde(rename = "upspeed", skip_serializing_if = "Option::is_none")]
    pub upspeed: Option<i64>,
}

impl TorrentInfo {
    pub fn new() -> TorrentInfo {
        TorrentInfo {
            added_on: None,
            amount_left: None,
            auto_tmm: None,
            availability: None,
            category: None,
            completed: None,
            completion_on: None,
            content_path: None,
            dl_limit: None,
            dlspeed: None,
            downloaded: None,
            downloaded_session: None,
            eta: None,
            f_l_piece_prio: None,
            force_start: None,
            hash: None,
            last_activity: None,
            magnet_uri: None,
            max_ratio: None,
            max_seeding_time: None,
            name: None,
            num_complete: None,
            num_incomplete: None,
            num_leechs: None,
            num_seeds: None,
            priority: None,
            progress: None,
            ratio: None,
            ratio_limit: None,
            reannounce: None,
            save_path: None,
            seeding_time: None,
            seeding_time_limit: None,
            seen_complete: None,
            seq_dl: None,
            size: None,
            state: None,
            super_seeding: None,
            tags: None,
            time_active: None,
            total_size: None,
            tracker: None,
            up_limit: None,
            uploaded: None,
            uploaded_session: None,
            upspeed: None,
        }
    }
}
/// Torrent state. See table here below for the possible values  | Value              | Description                                                   | | ------------------ | ------------------------------------------------------------- | | error              | Some error occurred, applies to paused torrents               | | missingFiles       | Torrent data files is missing                                 | | uploading          | Torrent is being seeded and data is being transferred         | | pausedUP           | Torrent is paused and has finished downloading                | | queuedUP           | Queuing is enabled and torrent is queued for upload           | | stalledUP          | Torrent is being seeded, but no connection were made          | | checkingUP         | Torrent has finished downloading and is being checked         | | forcedUP           | Torrent is forced to uploading and ignore queue limit         | | allocating         | Torrent is allocating disk space for download                 | | downloading        | Torrent is being downloaded and data is being transferred     | | metaDL             | Torrent has just started downloading and is fetching metadata | | pausedDL           | Torrent is paused and has NOT finished downloading            | | queuedDL           | Queuing is enabled and torrent is queued for download         | | stalledDL          | Torrent is being downloaded, but no connection were made      | | checkingDL         | Same as checkingUP, but torrent has NOT finished downloading  | | forcedDL           | Torrent is forced to downloading to ignore queue limit        | | checkingResumeData | Checking resume data on qBt startup                           | | moving             | Torrent is moving to another location                         | | unknown            | Unknown status                                                | 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "missingFiles")]
    MissingFiles,
    #[serde(rename = "uploading")]
    Uploading,
    #[serde(rename = "pausedUP")]
    PausedUp,
    #[serde(rename = "queuedUP")]
    QueuedUp,
    #[serde(rename = "stalledUP")]
    StalledUp,
    #[serde(rename = "checkingUP")]
    CheckingUp,
    #[serde(rename = "forcedUP")]
    ForcedUp,
    #[serde(rename = "allocating")]
    Allocating,
    #[serde(rename = "downloading")]
    Downloading,
    #[serde(rename = "metaDL")]
    MetaDl,
    #[serde(rename = "pausedDL")]
    PausedDl,
    #[serde(rename = "queuedDL")]
    QueuedDl,
    #[serde(rename = "stalledDL")]
    StalledDl,
    #[serde(rename = "checkingDL")]
    CheckingDl,
    #[serde(rename = "forcedDL")]
    ForcedDl,
    #[serde(rename = "checkingResumeData")]
    CheckingResumeData,
    #[serde(rename = "moving")]
    Moving,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for State {
    fn default() -> State {
        Self::Error
    }
}

