/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TorrentsProperties : The response is: - empty, if the torrent hash is invalid - otherwise, a JSON object with the following fields  NB: `-1` is returned if the type of the property is integer but its value is not known. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TorrentsProperties {
    /// Torrent save path
    #[serde(rename = "save_path", skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
    /// Torrent creation date (Unix timestamp)
    #[serde(rename = "creation_date", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<i64>,
    /// Torrent piece size (bytes)
    #[serde(rename = "piece_size", skip_serializing_if = "Option::is_none")]
    pub piece_size: Option<i64>,
    /// Torrent comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Total data wasted for torrent (bytes)
    #[serde(rename = "total_wasted", skip_serializing_if = "Option::is_none")]
    pub total_wasted: Option<i64>,
    /// Total data uploaded for torrent (bytes)
    #[serde(rename = "total_uploaded", skip_serializing_if = "Option::is_none")]
    pub total_uploaded: Option<i64>,
    /// Total data uploaded this session (bytes)
    #[serde(rename = "total_uploaded_session", skip_serializing_if = "Option::is_none")]
    pub total_uploaded_session: Option<i64>,
    /// Total data downloaded for torrent (bytes)
    #[serde(rename = "total_downloaded", skip_serializing_if = "Option::is_none")]
    pub total_downloaded: Option<i64>,
    /// Total data downloaded this session (bytes)
    #[serde(rename = "total_downloaded_session", skip_serializing_if = "Option::is_none")]
    pub total_downloaded_session: Option<i64>,
    /// Torrent upload limit (bytes/s)
    #[serde(rename = "up_limit", skip_serializing_if = "Option::is_none")]
    pub up_limit: Option<i64>,
    /// Torrent download limit (bytes/s)
    #[serde(rename = "dl_limit", skip_serializing_if = "Option::is_none")]
    pub dl_limit: Option<i64>,
    /// Torrent elapsed time (seconds)
    #[serde(rename = "time_elapsed", skip_serializing_if = "Option::is_none")]
    pub time_elapsed: Option<i64>,
    /// Torrent elapsed time while complete (seconds)
    #[serde(rename = "seeding_time", skip_serializing_if = "Option::is_none")]
    pub seeding_time: Option<i64>,
    /// Torrent connection count
    #[serde(rename = "nb_connections", skip_serializing_if = "Option::is_none")]
    pub nb_connections: Option<i64>,
    /// Torrent connection count limit
    #[serde(rename = "nb_connections_limit", skip_serializing_if = "Option::is_none")]
    pub nb_connections_limit: Option<i64>,
    /// Torrent share ratio
    #[serde(rename = "share_ratio", skip_serializing_if = "Option::is_none")]
    pub share_ratio: Option<f32>,
    /// When this torrent was added (unix timestamp)
    #[serde(rename = "addition_date", skip_serializing_if = "Option::is_none")]
    pub addition_date: Option<i64>,
    /// Torrent completion date (unix timestamp)
    #[serde(rename = "completion_date", skip_serializing_if = "Option::is_none")]
    pub completion_date: Option<i64>,
    /// Torrent creator
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// Torrent average download speed (bytes/second)
    #[serde(rename = "dl_speed_avg", skip_serializing_if = "Option::is_none")]
    pub dl_speed_avg: Option<i64>,
    /// Torrent download speed (bytes/second)
    #[serde(rename = "dl_speed", skip_serializing_if = "Option::is_none")]
    pub dl_speed: Option<i64>,
    /// Torrent ETA (seconds)
    #[serde(rename = "eta", skip_serializing_if = "Option::is_none")]
    pub eta: Option<i64>,
    /// Last seen complete date (unix timestamp)
    #[serde(rename = "last_seen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<i64>,
    /// Number of peers connected to
    #[serde(rename = "peers", skip_serializing_if = "Option::is_none")]
    pub peers: Option<i64>,
    /// Number of peers in the swarm
    #[serde(rename = "peers_total", skip_serializing_if = "Option::is_none")]
    pub peers_total: Option<i64>,
    /// Number of pieces owned
    #[serde(rename = "pieces_have", skip_serializing_if = "Option::is_none")]
    pub pieces_have: Option<i64>,
    /// Number of pieces of the torrent
    #[serde(rename = "pieces_num", skip_serializing_if = "Option::is_none")]
    pub pieces_num: Option<i64>,
    /// Number of seconds until the next announce
    #[serde(rename = "reannounce", skip_serializing_if = "Option::is_none")]
    pub reannounce: Option<i64>,
    /// Number of seeds connected to
    #[serde(rename = "seeds", skip_serializing_if = "Option::is_none")]
    pub seeds: Option<i64>,
    /// Number of seeds in the swarm
    #[serde(rename = "seeds_total", skip_serializing_if = "Option::is_none")]
    pub seeds_total: Option<i64>,
    /// Torrent total size (bytes)
    #[serde(rename = "total_size", skip_serializing_if = "Option::is_none")]
    pub total_size: Option<i64>,
    /// Torrent average upload speed (bytes/second)
    #[serde(rename = "up_speed_avg", skip_serializing_if = "Option::is_none")]
    pub up_speed_avg: Option<i64>,
    /// Torrent upload speed (bytes/second)
    #[serde(rename = "up_speed", skip_serializing_if = "Option::is_none")]
    pub up_speed: Option<i64>,
}

impl TorrentsProperties {
    /// The response is: - empty, if the torrent hash is invalid - otherwise, a JSON object with the following fields  NB: `-1` is returned if the type of the property is integer but its value is not known. 
    pub fn new() -> TorrentsProperties {
        TorrentsProperties {
            save_path: None,
            creation_date: None,
            piece_size: None,
            comment: None,
            total_wasted: None,
            total_uploaded: None,
            total_uploaded_session: None,
            total_downloaded: None,
            total_downloaded_session: None,
            up_limit: None,
            dl_limit: None,
            time_elapsed: None,
            seeding_time: None,
            nb_connections: None,
            nb_connections_limit: None,
            share_ratio: None,
            addition_date: None,
            completion_date: None,
            created_by: None,
            dl_speed_avg: None,
            dl_speed: None,
            eta: None,
            last_seen: None,
            peers: None,
            peers_total: None,
            pieces_have: None,
            pieces_num: None,
            reannounce: None,
            seeds: None,
            seeds_total: None,
            total_size: None,
            up_speed_avg: None,
            up_speed: None,
        }
    }
}

