/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TorrentsTrackers {
    /// Tracker url
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Tracker status. See the table below for possible values  | Value | Description                                                                        | | ----- | ---------------------------------------------------------------------------------- | | 0     | Tracker is disabled (used for DHT, PeX, and LSD)                                   | | 1     | Tracker has not been contacted yet                                                 | | 2     | Tracker has been contacted and is working                                          | | 3     | Tracker is updating                                                                | | 4     | Tracker has been contacted, but it is not working (or doesn't send proper replies) | 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Tracker priority tier. Lower tier trackers are tried before higher tiers. Tier numbers are valid when `>= 0`, `< 0` is used as placeholder when `tier` does not exist for special entries (such as DHT).
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<i64>,
    /// Number of peers for current torrent, as reported by the tracker
    #[serde(rename = "num_peers", skip_serializing_if = "Option::is_none")]
    pub num_peers: Option<i64>,
    /// Number of seeds for current torrent, asreported by the tracker
    #[serde(rename = "num_seeds", skip_serializing_if = "Option::is_none")]
    pub num_seeds: Option<i64>,
    /// Number of leeches for current torrent, as reported by the tracker
    #[serde(rename = "num_leeches", skip_serializing_if = "Option::is_none")]
    pub num_leeches: Option<i64>,
    /// Number of completed downlods for current torrent, as reported by the tracker
    #[serde(rename = "num_downloaded", skip_serializing_if = "Option::is_none")]
    pub num_downloaded: Option<i64>,
    /// Tracker message (there is no way of knowing what this message is - it's up to tracker admins)
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
}

impl TorrentsTrackers {
    pub fn new() -> TorrentsTrackers {
        TorrentsTrackers {
            url: None,
            status: None,
            tier: None,
            num_peers: None,
            num_seeds: None,
            num_leeches: None,
            num_downloaded: None,
            msg: None,
        }
    }
}
/// Tracker status. See the table below for possible values  | Value | Description                                                                        | | ----- | ---------------------------------------------------------------------------------- | | 0     | Tracker is disabled (used for DHT, PeX, and LSD)                                   | | 1     | Tracker has not been contacted yet                                                 | | 2     | Tracker has been contacted and is working                                          | | 3     | Tracker is updating                                                                | | 4     | Tracker has been contacted, but it is not working (or doesn't send proper replies) | 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum Status {
    Variant0 = 0,
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant0 => "0",
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
            Self::Variant4 => "4",
        })
    }
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant0
    }
}

