/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TorrentsCategory {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "savePath", skip_serializing_if = "Option::is_none")]
    pub save_path: Option<String>,
}

impl TorrentsCategory {
    pub fn new() -> TorrentsCategory {
        TorrentsCategory {
            name: None,
            save_path: None,
        }
    }
}

