/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TorrentsFiles {
    /// File index
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i64>,
    /// File name (including relative path)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// File size (bytes)
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// File progress (percentage/100)
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<f32>,
    /// File priority. See possible values here below  | Value | Description      | | ----- | ---------------- | | 0     | Do not download  | | 1     | Normal priority  | | 6     | High priority    | | 7     | Maximal priority | 
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    /// True if file is seeding/complete
    #[serde(rename = "is_seed", skip_serializing_if = "Option::is_none")]
    pub is_seed: Option<bool>,
    /// The first number is the starting piece index and the second number is the ending piece index (inclusive)
    #[serde(rename = "piece_range", skip_serializing_if = "Option::is_none")]
    pub piece_range: Option<Vec<i64>>,
    /// Percentage of file pieces currently available (percentage/100)
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<f32>,
}

impl TorrentsFiles {
    pub fn new() -> TorrentsFiles {
        TorrentsFiles {
            index: None,
            name: None,
            size: None,
            progress: None,
            priority: None,
            is_seed: None,
            piece_range: None,
            availability: None,
        }
    }
}
/// File priority. See possible values here below  | Value | Description      | | ----- | ---------------- | | 0     | Do not download  | | 1     | Normal priority  | | 6     | High priority    | | 7     | Maximal priority | 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "7")]
    Variant7,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Variant0
    }
}

