/*
 * qBittorrent WebUI API
 *
 * - All API methods are under `/api/v2/APIName/methodName`, where `APIName` is a certain subgroup of API methods whose functionality is related. - Either `GET` or `POST` can be used as the request type for all API methods. - All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#authentication) (except the `/api/v2/auth/login` method itself, obviously). 
 *
 * The version of the OpenAPI document: 2.11.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferInfo : The response is a JSON object with the following fields  In addition to the above in partial data requests (see [Get partial data](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#get-partial-data) for more info): 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferInfo {
    /// Global download rate (bytes/s)
    #[serde(rename = "dl_info_speed", skip_serializing_if = "Option::is_none")]
    pub dl_info_speed: Option<i64>,
    /// Data downloaded this session (bytes)
    #[serde(rename = "dl_info_data", skip_serializing_if = "Option::is_none")]
    pub dl_info_data: Option<i64>,
    /// Global upload rate (bytes/s)
    #[serde(rename = "up_info_speed", skip_serializing_if = "Option::is_none")]
    pub up_info_speed: Option<i64>,
    /// Data uploaded this session (bytes)
    #[serde(rename = "up_info_data", skip_serializing_if = "Option::is_none")]
    pub up_info_data: Option<i64>,
    /// Download rate limit (bytes/s)
    #[serde(rename = "dl_rate_limit", skip_serializing_if = "Option::is_none")]
    pub dl_rate_limit: Option<i64>,
    /// Upload rate limit (bytes/s)
    #[serde(rename = "up_rate_limit", skip_serializing_if = "Option::is_none")]
    pub up_rate_limit: Option<i64>,
    /// DHT nodes connected to
    #[serde(rename = "dht_nodes", skip_serializing_if = "Option::is_none")]
    pub dht_nodes: Option<i64>,
    /// Connection status. See possible values here below  Possible values of connection_status: | Value        | | ------------ | | connected    | | firewalled   | | disconnected | 
    #[serde(rename = "connection_status", skip_serializing_if = "Option::is_none")]
    pub connection_status: Option<String>,
    /// True if torrent queueing is enabled
    #[serde(rename = "queueing", skip_serializing_if = "Option::is_none")]
    pub queueing: Option<bool>,
    /// True if alternative speed limits are enabled
    #[serde(rename = "use_alt_speed_limits", skip_serializing_if = "Option::is_none")]
    pub use_alt_speed_limits: Option<bool>,
    /// Transfer list refresh interval (milliseconds)
    #[serde(rename = "refresh_interval", skip_serializing_if = "Option::is_none")]
    pub refresh_interval: Option<i64>,
}

impl TransferInfo {
    /// The response is a JSON object with the following fields  In addition to the above in partial data requests (see [Get partial data](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-5.0)#get-partial-data) for more info): 
    pub fn new() -> TransferInfo {
        TransferInfo {
            dl_info_speed: None,
            dl_info_data: None,
            up_info_speed: None,
            up_info_data: None,
            dl_rate_limit: None,
            up_rate_limit: None,
            dht_nodes: None,
            connection_status: None,
            queueing: None,
            use_alt_speed_limits: None,
            refresh_interval: None,
        }
    }
}

